#!/usr/bin/env python

import sys
import os
from subprocess import call

def add_iface_to_bridge():
    try:
        iface = sys.argv[1]
        bridge = os.environ["bridge_%s" % iface]
        cmd = ["brctl", "addif", bridge, iface]
        call(cmd)
        iface_up = ["ip", "link", "set", iface, "up"]
        call(iface_up)
    except KeyError, e:
        print str(e)


add_iface_to_bridge()    
